name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
categories:
  - title: "🚀 Features"
    labels:
      - "type:feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "type:bug"
  - title: "🧰 Maintenance"
    labels:
      - "type:chore"
      - "tech-debt"
  - title: "📝 Documentation"
    labels:
      - "type:docs"
  - title: "🔬 Spikes & Research"
    labels:
      - "type:spike"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'
autolabeler:
  - label: "type:feature"
    title:
      - '/^feat(\(.+\))?!?:/i'
  - label: "type:bug"
    title:
      - '/^fix(\(.+\))?!?:/i'
  - label: "type:docs"
    title:
      - '/^docs(\(.+\))?!?:/i'
  - label: "type:chore"
    title:
      - '/^(chore|refactor|test|build|ci|perf|style)(\(.+\))?!?:/i'
  - label: "type:spike"
    title:
      - '/^spike(\(.+\))?!?:/i'
version-resolver:
  patch:
    labels:
      - "breaking"
      - "type:feature"
      - "type:bug"
      - "type:chore"
      - "type:docs"
      - "type:spike"
  default: patch
